// <auto-generated />
using System;
using ErpPortal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErpPortal.Infrastructure.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ErpPortalDbContext))]
    [Migration("20250612050945_VeriModeliDuzeltmesi")]
    partial class VeriModeliDuzeltmesi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ErpPortal.Domain.Entities.ShopOrder", b =>
                {
                    b.Property<string>("OrderNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PartDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PartNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PlannedFinishDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderNo");

                    b.ToTable("ShopOrders");
                });

            modelBuilder.Entity("ErpPortal.Domain.Entities.ShopOrderOperation", b =>
                {
                    b.Property<string>("OrderNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OperationNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualFinishDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ETag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EfficiencyFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("InterruptionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSyncPending")
                        .HasColumnType("bit");

                    b.Property<decimal>("LaborRunFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LaborSetupTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastInterruptionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastSyncTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MachRunFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MachSetupTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MoveTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OpFinishDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpSequenceNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("OpStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperStatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationSchedStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutsideOpBackflush")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OutsideOpComplete")
                        .HasColumnType("bit");

                    b.Property<string>("ParallelOperation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QtyComplete")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QtyScrapped")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantityCompleted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantityScrapped")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QueueTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReleaseNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("RevisedQtyDue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RunTimeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchedDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SequenceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("TotalInterruptionDuration")
                        .HasColumnType("time");

                    b.Property<string>("WorkCenterCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("WorkCenterId")
                        .HasColumnType("int");

                    b.Property<string>("WorkCenterNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderNo", "OperationNo");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("ShopOrderOperations");
                });

            modelBuilder.Entity("ErpPortal.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ErpPortal.Domain.Entities.UserWorkCenter", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkCenterId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "WorkCenterId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("UserWorkCenters");
                });

            modelBuilder.Entity("ErpPortal.Domain.Entities.WorkCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WorkCenters");
                });

            modelBuilder.Entity("ErpPortal.Domain.Entities.WorkLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OperationNo")
                        .HasColumnType("int");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrderNo", "OperationNo", "UserId", "StartTime");

                    b.ToTable("WorkLogs");
                });

            modelBuilder.Entity("ErpPortal.Domain.Entities.ShopOrderOperation", b =>
                {
                    b.HasOne("ErpPortal.Domain.Entities.ShopOrder", "ShopOrder")
                        .WithMany("Operations")
                        .HasForeignKey("OrderNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpPortal.Domain.Entities.WorkCenter", "WorkCenter")
                        .WithMany("Operations")
                        .HasForeignKey("WorkCenterId");

                    b.Navigation("ShopOrder");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("ErpPortal.Domain.Entities.UserWorkCenter", b =>
                {
                    b.HasOne("ErpPortal.Domain.Entities.User", "User")
                        .WithMany("UserWorkCenters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErpPortal.Domain.Entities.WorkCenter", "WorkCenter")
                        .WithMany("UserWorkCenters")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("ErpPortal.Domain.Entities.WorkLog", b =>
                {
                    b.HasOne("ErpPortal.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErpPortal.Domain.Entities.ShopOrder", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("ErpPortal.Domain.Entities.User", b =>
                {
                    b.Navigation("UserWorkCenters");
                });

            modelBuilder.Entity("ErpPortal.Domain.Entities.WorkCenter", b =>
                {
                    b.Navigation("Operations");

                    b.Navigation("UserWorkCenters");
                });
#pragma warning restore 612, 618
        }
    }
}
